management:
  endpoint:
    health:
      probes:
        enabled: true

acme:
  security:
    header-filter:
      enabled: ${ACME_SECURITY_HEADER_FILTER_ENABLED:true}
      ignored-headers: '${ACME_SECURITY_HEADER_FILTER_IGNORED_HEADERS:{"user-agent":["GLB-Client/1.35+","HealthChecker/1.0"]}}'

logging:
  level:
    org.acme.demo.security: ${LOG_ACME_SECURITY_LVL:DEBUG}
